# Generated by Django 5.1.15 on 2026-09-23 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('car_make', models.CharField(blank=True, default='', max_length=100)),
                ('car_model', models.CharField(blank=True, default='', max_length=100)),
                ('car_year', models.IntegerField(blank=True, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('initial', 'Initial Inquiry'), ('gathering_info', 'Gathering Vehicle Details'), ('diagnosed', 'Diagnosis Complete'), ('booking_pending', 'Booking in Progress'), ('booked', 'Appointment Booked')], default='initial', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('mechanic', 'Senior Mechanic'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('ai_invoked', models.BooleanField(default=False, help_text='True if response consumed Gemini API tokens')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_issue', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low - Safe to drive temporarily'), ('moderate', 'Moderate - Schedule service soon'), ('critical', 'Critical - Do NOT drive, towing recommended')], default='moderate', max_length=20)),
                ('confidence_score', models.FloatField(default=0.85)),
                ('symptoms', models.JSONField(default=list, help_text='List of identified symptoms')),
                ('possible_causes', models.JSONField(default=list, help_text='List of probable root causes')),
                ('recommended_repairs', models.JSONField(default=list, help_text='List of actionable repairs or parts')),
                ('estimated_cost_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estimated_cost_max', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('diy_friendly', models.BooleanField(default=False)),
                ('summary_notes', models.TextField(blank=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='api.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=32, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=30)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('service_type', models.CharField(default='Mobile Mechanic On-Site', max_length=100)),
                ('mechanic_name', models.CharField(default='Marcus Vance (Master Automotive Technician)', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.diagnosis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('other', 'Other')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('analysis_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_attachments', to='api.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
