# Generated by Django 5.1.15 on 2026-09-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Unique client device or user identifier', max_length=120),
        ),
    ]
